### ISSUE TITLE
Image not draw on canvas

### ISSUE THREAD

**Issue by mohitmadaan27** [martinbaciga/android-drawing-canvas#3]
i am doing this by 
`mDrawCanvas.drawBitmap(bitmap, null, new Rect(100, 100, 200, 150),mDrawPaint);`

but it is not drawing drawable

**Comment by martinbaciga** [comment]
Hi, could you be more specific on what you want to do? 

Anyway i think that what you want to do should go inside the onDraw() method in the DrawCanvas class.

**Comment by mohitmadaan27** [comment]
i want to draw on image.like i want to select picture from gallery and draw on it and i used this code but it is not working

**Comment by martinbaciga** [comment]
Ok. I don't know exactly how can you draw the picture on the canvas, i should check that. But like i said before i'm pretty sure that if drawBitmap(..) were the right function, that should go inside the onDraw() method in the DrawCanvas class. You can do that for test proposes but then you should modularize that.

I made a more complex drawing view for another project and what i did to accomplish what you're saying is to add an ImageView over the DrawingCanvas component.
